services:
    db:
        image: postgres:16
        container_name: notes_db
        restart: always
        environment:
            POSTGRES_DB: notes
            POSTGRES_USER: notes
            POSTGRES_PASSWORD: notes
        ports:
           - "5432:5432"
        volumes:
           - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: